<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Invoice <?php echo ! empty( $payment ) ? '#' . $payment->getId() : ''; ?></title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel='stylesheet' id='google-fonts-css' href='//fonts.googleapis.com/css?family=PT+Sans%3A400%7COxygen%3A400&#038;ver=5.5.1' type='text/css' media='all'/>
    <style>
        body {
            margin-top: 20px;
            background: #eee;
            font-family: 'Oxygen';
        }

        .invoice {
            padding: 30px;
        }

        .invoice h2 {
            margin-top: 0px;
            line-height: 0.8em;
        }

        .invoice .small {
            font-weight: 300;
        }

        .invoice hr {
            margin-top: 10px;
            border-color: #ddd;
        }

        .invoice .table tr.line {
            border-bottom: 1px solid #ccc;
        }

        .invoice .table td {
            border: none;
        }

        .grid {
            position: relative;
            width: 100%;
            background: #fff;
            color: #666666;
            border-radius: 2px;
            margin-bottom: 25px;
            box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.1);
        }

        @media print {
            .btn-info {
                display: none;
            }
        }
    </style>
</head>
<?php
if ( ! empty( $extras ) ) {
	$ict_codes = json_decode( $extras );
} else {
	$ict_codes = false;
}
?>
<body class="">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p><a href="javascript:void(0);" onclick="window.print();" class="btn btn-info rounded-0">Print Invoice</a></p>
        </div>
        <!-- BEGIN INVOICE -->
        <div class="col-md-12">
            <div class="grid invoice">
                <div class="grid-body">
                    <div class="invoice-title">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <img src="https://bookme.webmeeting.video/wp-content/uploads/2020/02/Logo.png" alt="" height="60">
                                <p class="mt-3"><i>Generated by Headroom on behalf of the Professional for services rendered via
                                        <a href="https://www.headroom.co.za">www.headroom.co.za</a></i></p>
                            </div>
                            <div class="col-md-12 text-center mt-3">
                                <h3>Tax Invoice</h3>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12 text-md-right">
                            <address>
                                <span class="invoiceNumber">Invoice Number: #<?php echo ! empty( $payment ) ? $payment->getId() : 'N/A'; ?></span><br>
								<?php
								if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->invoice_date ) ) {
									?>
                                    <span class="invoice-date">Date: <?php echo $ict_codes[0]->invoice_date; ?></span><br>
									<?php
								}
								?>
                                <span class="staffName"><?php echo $staff->getFullName(); ?></span><br>
								<?php
								if ( ! empty( $professional_address ) ) {
									echo '<span>' . $professional_address . '</span><br>';
								}

								/*if ( ! empty( $category->getName() ) ) { ?>
                                    <span class="catName"><?php echo $category->getName(); ?></span><br>
									<?php
								}*/

								if ( ! empty( $practise_number ) ) {
									echo '<span>Practice No.: ' . $practise_number . '</span><br>';
								}

								if ( ! empty( $professional_reg_number ) ) {
									echo '<span>Registration No.: ' . $professional_reg_number . '</span><br>';
								}
								if ( ! empty( $professional_reg_number ) ) {
									echo '<span>VAT Registration No.: ' . $vat_number . '</span><br>';
								}

								if ( ! empty( $staff->getInfo() ) ) {
									echo '<span>' . $staff->getInfo() . '</span>';
								}
								?>
                            </address>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <address>
                                <span>To: <?php echo $customer->getFullName(); ?></span><br>
								<?php
								if ( ! empty( $customer->getPostCode() ) ) {
									echo $customer->getPostCode() . ', ';
								}

								if ( ! empty( $customer->getState() ) ) {
									echo $customer->getState() . ', ';
								}

								if ( ! empty( $customer->getCity() ) ) {
									echo $customer->getCity() . '<br>';
								}

								if ( ! empty( $customer->getStreetNumber() ) ) {
									echo $customer->getStreetNumber() . ', ';
								}

								if ( ! empty( $customer->getStreet() ) ) {
									$trim = explode( ',', $customer->getStreet() );
									echo end( $trim ) . ', ';
								}

								if ( ! empty( $customer->getCountry() ) ) {
									echo $customer->getCountry() . '<br>';
								}

								$med_name = ! empty( $med_aid_name ) ? $med_aid_name : 'N/A';
								$mem_no   = ! empty( $membership_no ) ? $membership_no : 'N/A';
								$dp_code  = ! empty( $dpendent_code ) ? $dpendent_code : 'N/A';
								echo 'Medical Aid: ' . $med_name . '<br>';
								echo 'Membership No.: ' . $mem_no . '<br>';
								echo 'Dependent Code: ' . $dp_code;
								?>
                            </address>
                            <table class="table table-striped table-responsive-md table-bordered">
                                <thead>
                                <tr class="line">
                                    <td><strong>#</strong></td>
                                    <td class="text-left"><strong>Date</strong></td>
                                    <td class="text-left"><strong>ICD 10 Code</strong></td>
                                    <td class="text-left"><strong>Tariff Code</strong></td>
                                    <td class="text-left"><strong>Session Detail</strong></td>
                                    <td class="text-right"><strong>Amount</strong></td>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $backend_price = ! empty( $backend_price ) ? $backend_price : 0;
                                $total_price   = ! empty( $payment ) ? $payment->getTotal() : $backend_price;
                                $vat_price     = ! empty( $vat_number ) ? $total_price * 0.15 : 0;
                                ?>
                                <tr>
                                    <td>1</td>
                                    <td class="text-left"><?php echo esc_html( date( 'F, y l, g:i a', strtotime( $appointment->getStartDate() ) ) ); ?></td>
                                    <td class="text-left">
										<?php
										if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->ict_code ) ) {
											echo $ict_codes[0]->ict_code;
										} else {
											echo "N/A";
										}
										?>
                                    </td>
                                    <td class="text-left">
										<?php
										if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->tariff_code ) ) {
											echo $ict_codes[0]->tariff_code;
										} else {
											echo "N/A";
										}
										?>
                                    </td>
                                    <td>
                                        <p class="mb-1"><strong>Service: </strong> <?php echo esc_html( $service->getTitle() ); ?></p>
                                        <p class="mb-1"><strong>Duration: </strong> <?php echo esc_html( $service->getDuration() ) / 60; ?> minutes
                                        </p>
                                        <p class="mb-1"><strong>Professional: </strong> <?php echo esc_html( $staff->getFullName() ); ?></p>
                                    </td>
                                    <td class="text-right">R
										<?php
										if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->manual_price ) ) {
											echo esc_html( number_format( $ict_codes[0]->manual_price, 2 ) );
										} else {
											echo esc_html( $total_price );
										}
										?>
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="4"></td>
                                    <td class="text-right"><strong>Price excl. VAT</strong></td>
                                    <td class="text-right">
                                        <strong>R
											<?php
											if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->manual_price ) ) {
												echo esc_html( number_format( $ict_codes[0]->manual_price, 2 ) );
											} else {
												echo esc_html( $total_price );
											}
											?>
                                        </strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td class="text-right"><strong>VAT (15%)</strong></td>
                                    <td class="text-right">
                                        <strong>R
											<?php
											if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->manual_price ) ) {
												echo ! empty( $vat_number ) ? esc_html( $ict_codes[0]->manual_price ) * 0.15 : 0;
											} else {
												echo esc_html( number_format( $vat_price, 2 ) );
											}
											?>
                                        </strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td class="text-right"><strong>Total incl. VAT</strong></td>
                                    <td class="text-right"><strong>R
											<?php
											if ( ! empty( $ict_codes ) && ! empty( $ict_codes[0]->manual_price ) ) {
												$vat = ! empty( $vat_number ) ? esc_html( $ict_codes[0]->manual_price ) * 0.15 : 0;
												echo esc_html( number_format( $ict_codes[0]->manual_price + $vat, 2 ) );
											} else {
												echo esc_html( number_format( $total_price + $vat_price, 2 ) );
											}
											?>
                                        </strong></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
							<?php if ( isset( $ict_codes ) && ! isset( $ict_codes[0]->manual_price ) ) { ?>
                                <p class="text-center" style="text-decoration: underline;"><strong>This invoice has already been paid.</strong></p>
							<?php } ?>
                            <p class="text-center">
                                <i>Kindly direct any queries to <a href="mailto:admin@headroom.co.za">admin@headroom.co.za</a></i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END INVOICE -->
    </div>
</div>
</body>
</html>